export const ProgrammingTasks = {
  [0]: {
    title: "Zestaw zadań nr 1",
    1: {
      Task: "Co to jest debugowanie?",
      Options: {
        a: "Proces pisania dokumentacji do aplikacji.",
        b: "Proces szukania i naprawiania błędów w kodzie.",
        c: "Tworzenie kopii zapasowych projektów.",
      },
      Right_answer: "b",
      Complete: false,
      answerType: "Choose",
    },
    2: {
      Task: "Który typ bazy danych jest najczęściej używany do przechowywania danych w formacie klucz-wartość?",
      Options:{
      a: "Relacyjna baza danych",
      b: "NoSQL",
      c: "Baza grafowa",
      },
      Right_answer: "a",
      Complete: false,
      answerType: "Choose",
    },
    3: {
      Task: "Utwórz zmienną o nazwie carName i przypisz jej wartość Volvo.",
      Right_answer: "var carName = 'Volvo';",
      answerType: "Type",
      Complete: false,
    },
    4: {
      Task: "Co to jest algorytm?",
      Options:{
      a: "Zbiór kroków do rozwiązania konkretnego problemu.",
      b: "Forma graficzna przedstawiająca dane.",
      c: "Rodzaj języka programowania.",
      },
      Right_answer: "b",
      answerType: "Choose",
      Complete: false,
    },
    5: {
      Task: "Co to jest algorytm?",
      Options:{
      a: "Zbiór kroków do rozwiązania konkretnego problemu.",
      b: "Forma graficzna przedstawiająca dane.",
      c: "Rodzaj języka programowania.",
      },
      Right_answer: "b",
      answerType: "Choose",
      Complete: false,
    },
  },
  [1]: {
    title: "Zestaw zadań nr 2",
    Question1: {
      Task: "Która operacja CNC polega na usuwaniu materiału za pomocą ruchu obrotowego narzędzia?",
      Answer_a: "Toczenie",
      Answer_b: "Wiercenie",
      Answer_c: "Frezowanie",
      Right_answer: "c",
      answerType: "Choose",
    },
    Question2: {
      Task: "Co to jest SQL?",
      Answer_a: "Język używany do tworzenia stron internetowych.",
      Answer_b: "Język zapytań do zarządzania bazami danych.",
      Answer_c: "Narzędzie do projektowania interfejsów użytkownika.",
      Right_answer: "b",
      answerType: "Choose",
    },
    Question3: {
      Task: "Kasia ma 8 cukierków, a Ania ma 5 cukierków. Ile cukierków mają razem? Zapisz równanie.",
      Right_answer: "8 + 5 = 13",
      answerType: "Type",
    },
    Question4: {
      Task: "Jakie są dwa główne typy oprogramowania?",
      Answer_a: "Oprogramowanie systemowe i użytkowe",
      Answer_b: "Oprogramowanie do gier i oprogramowanie edukacyjne",
      Answer_c: "Oprogramowanie płatne i darmowe",
      Right_answer: "a",
      answerType: "Choose",
    },
    Question5: {
      Task: "Kto dowodził wojskami polsko-litewskimi w bitwie pod Grunwaldem w 1410 roku?",
      Answer_a: "Władysław Jagiełło",
      Answer_b: "Kazimierz Jagiellończyk",
      Answer_c: "Jan III Sobieski",
      Right_answer: "a",
      answerType: "Choose",
    },
  },
};
