import type { Metadata } from "next";
import "./globals.css";

import { Nunito } from 'next/font/google'
import Login from "./components/login";
import Providers from "./providers";
const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hackaton",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={font.className}>
          <Providers>
            <div className="flex w-full relative h-svh">{children}</div>
            <Login />
          </Providers>
        </body>
      </html>
  );
}
